#!/usr/bin/env bash

cat <<EOF | kubectl apply -f -

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py3web-prj-deployment
  namespace: default
  labels:
    app: web
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: py3web-prj-deployment
  template:
    metadata:
      labels:
        app: py3web-prj-deployment
    spec:
      containers:
      - name: py3web
        image: o1gerd/py3web:$CI_PIPELINE_ID
        ports:
        - containerPort: 32400

---
apiVersion: v1
kind: Service
metadata:
  name: py3web-prj-service
  namespace: default
spec:
  ports:
   - protocol: TCP
     port: 32400
  selector:
    app: py3web-prj-deployment
  type: NodePort

EOF